import { Component, OnInit } from '@angular/core';
import { ContentfulService } from 'src/app/core/services/contentful/contentful.service';
import { SkillFields } from 'src/app/models/skill/skillFields';
import { Entry } from 'contentful';
import { TechnologyLayerDescription } from 'src/app/models/technologyLayerDescription/technologyLayerDescription';
import { ApexChart, ApexTitleSubtitle, ApexAxisChartSeries, ApexXAxis, ApexTheme } from 'ng-apexcharts';
import { SkillType } from 'src/app/models/skill/skillTypes';
import { TechnologyLayerType } from 'src/app/models/technologyLayerDescription/technologyLayerType'; // used in UI Component

@Component({
  selector: 'app-myskills',
  templateUrl: './myskills.component.html',
  styleUrls: ['./myskills.component.scss']
})
export class MyskillsComponent implements OnInit {

  private skills: SkillFields[];
  private technologyDescriptions: TechnologyLayerDescription[];

  // chart stuff
  private chartType: ApexChart;
  private chartTheme: ApexTheme;

  private techChartTitle: ApexTitleSubtitle;
  private langChartTitle: ApexTitleSubtitle;

  private frontendTechChartSeries: ApexAxisChartSeries;
  private frontendTechChartXaxis: ApexXAxis;
  private frontendLangChartSeries: ApexAxisChartSeries;
  private frontendLangChartXaxis: ApexXAxis;

  constructor(private contentfulService: ContentfulService) { }

  ngOnInit() {
    this.contentfulService.getSkillPageContent().then((skillEntries: Entry<SkillFields>[]) => {
      console.log('Meine Skill-Entries: ', skillEntries);
      this.skills = this.resolveInnerEntriesOfType(skillEntries);
      this.initializeCharts();
    }).catch(error => {
      console.log('Contentful-API: Es wurden keine Skills gefunden: ', error);
    });

    this.contentfulService.getTechnologyLayerDescriptionContent().then((techdescEntries: Entry<TechnologyLayerDescription>[]) => {
      console.log('Meine TechnologyDescription-Entries: ', techdescEntries);
      this.technologyDescriptions = this.resolveInnerEntriesOfType(techdescEntries);
    }).catch(error => {
      console.log('Contentful-API: Es wurden keine Technology-Beschreibungen gefunden: ', error);
    });
  }

/**
 * resolving the raw data fields as an array of Entry Collection from API Definition
 * @param entries Entry Collection with has the raw data input from Type T
 * @returns delivers the raw data structure of type T as an data array
 */
  resolveInnerEntriesOfType<T>(entries: Entry<T>[]): T[] {
    const innerEntryTypes: T[] = [];

    entries.forEach(entry => {
      innerEntryTypes.push(entry.fields);
    });

    return innerEntryTypes;
  }

/**
 * Creates firstly the basic chart theme, with chart type and color theme.
 * Creates secondly the chart titles of all visible charts.
 * Creates chart series data and xaxis labeling of every chart based on fetched data in this.skills
 */
  initializeCharts() {
    this.generateChartsBasicTheme();
    this.setChartTitles();
    this.setChartSeriesAndXaxisLabels(SkillType.frontend);
  }

/**
 * Generates the basic chart type and color theme for every visual chart
 */
  generateChartsBasicTheme() {
    const chart: ApexChart = {
      type: 'bar'
    };

    this.chartType = chart;

    this.chartTheme = {
      monochrome: {
          enabled: true,
          color: '#6597e7',
          shadeTo: 'light',
          shadeIntensity: 0.65
        }
    };
  }


/**
 * Generates the title of every visual chart
 */
  setChartTitles() {
    this.techChartTitle = {
      text: 'Mein aktueller Technologie-Stack:'
    };
    this.langChartTitle = {
      text: 'Kenntnisse in Programmiersprachen:'
    };
  }

/**
 * Based on the Skill Type the data of this.skills will be resolved into the specific chart into chartseries and,
 * secondly, into the seperate xAxis Labeling
 * @param skillType The chartType of the chart, in which the result data will be stored
 */
  setChartSeriesAndXaxisLabels(skillType: SkillType) {
    const techToolTipDesc = 'Skill-Niveau (in %)';
    const langToolTipDesc = techToolTipDesc;

    switch (skillType) {
      case SkillType.frontend: {

        // const techSeries: number[] = [30, 40, 35, 50, 49, 60, 70, 91, 125];
        const techSeries = this.resolveChartSeriesData(false, skillType);

        this.frontendTechChartSeries = [{
          name: techToolTipDesc,
          data: techSeries
        }];

        const langSeries = this.resolveChartSeriesData(true, skillType);

        this.frontendLangChartSeries = [{
          name: langToolTipDesc,
          data: langSeries
        }];

        break;
      }
      default: {
        // TO DO
        console.log('Kein bisheriges Handling des SkillTypes');
      }
    }
  }

/**
 * based on the skilltype and the filtered skills, the axis labeling will be generated by chart type
 * @param skillType as known as the chart type, to generate xaxis labeling for.
 * @param isLanguageProperty is chartType a TechStack one, or a Language Chart?
 * @param filteredSkills the filtered skills, where the axis labeling will be extracted from
 */
  setXaxis(skillType: SkillType, isLanguageProperty: boolean, filteredSkills: SkillFields[]) {
    switch (skillType) {
      case SkillType.frontend: {

        // const xaxis: number[] = [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999];

        const xaxis: string[] = [];

        filteredSkills.forEach(skill => {
          xaxis.push(skill.title);
        });

        if (!isLanguageProperty) {
          this.frontendTechChartXaxis = {
            categories: xaxis
          };
        } else {
          this.frontendLangChartXaxis = {
            categories: xaxis
          };
        }
        break;
      }
      default: {
        // TO DO
        console.log('Kein bisheriges Handling des SkillTypes');
      }
    }

  }

/**
 * Based on the skill type, the chart series data will be found and stored within the on
 * skillType dependend chart type
 * @param isLanguageProperty chartSeries generation for TechStack chart or Language Chart?
 * @param skillType as known as the chartType
 */
  resolveChartSeriesData(isLanguageProperty: boolean, skillType: SkillType): number[] {

    const seriesData: number[] = [];

    switch (skillType) {

      case SkillType.frontend: {

        const filteredSkills: SkillFields[] = this.skills.filter(skill => {
            return this.checkSkillField(skill, isLanguageProperty, skillType);
          });

        filteredSkills.sort((a, b) => b.level - a.level); // Größter Value zuerst, von links nach rechts
        console.log('filteredSkills (Nur Tech oder Lang): ', filteredSkills);

        filteredSkills.forEach(skill => {
          seriesData.push(skill.level);
        });

        // Erzeuge zugehörig auch die X-Achsen-Beschriftungen für Tech oder Lang
        this.setXaxis(skillType, isLanguageProperty, filteredSkills);
        break;
      }
      default: {
        // TO DO
        console.log('Kein Handling berücksichtigt');
      }
    }

    return seriesData;
  }

/**
 * Does the current Skill match the isLanguageProperty and does the skill.type lists the current SkillType?
 * @param skill will be checked
 * @param isLanguageProperty nothing to say (TechStack or Language)
 * @param skillType the current chart Type
 */
  checkSkillField(skill: SkillFields, isLanguageProperty: boolean, skillType: SkillType): boolean {
    let isCorrect = false;

    if (skill.isLanguage !== isLanguageProperty) {
            isCorrect = false;
            return isCorrect;
          }

    skill.type.forEach(skilltype => {
              if (skilltype === skillType) {
                isCorrect = true;
              }
            }
          );
    return isCorrect;
  }

  getTechnologyLayerDescriptions(type: TechnologyLayerType): TechnologyLayerDescription {
    return this.technologyDescriptions.find(singleDescription => {
      return singleDescription.type === type;
    });
  }
}
